version: '3.2'
services:
  fetch-oef:
    container_name: fetch-oef
    build:
      context: ./prediction-market-oef
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "3333:10000"
  fetch-aea:
    container_name: fetch-aea
    build:
      context: ./prediction-market-aea
      dockerfile: ./Dockerfile
