version: '3.2'
services:
  oef-node:
    image: "fetchai/oef-search:0.7"
    ports:
      - "10000:10000"
      - "20000:20000"
      - "40000:40000"
      - "7500:7500"
    volumes:
      - "./prediction-market-oef/config:/config"
    command:
      - "/config/node_config.json"
    expose:
      - "10000"

  fetch-aea:
    container_name: fetch-aea
    build:
      context: ./prediction-market-aea
      dockerfile: ./Dockerfile
