version: '3.2'
services:
  oef-node:
    container_name: oef-node
    build:
      context: ./prediction-market-oef
      dockerfile: ./Dockerfile
    ports:
      - "10000:10000"
      - "20000:20000"
      - "40000:40000"
      - "7500:7500"
    volumes:
      - "./prediction-market-oef/config:/config"
    command:
      - "/config/node_config.json"
    expose:
      - "10000"
    logging:
      driver: none

  fetch-aea:
    container_name: fetch-aea
    build:
      context: ./prediction-market-aea
      dockerfile: ./Dockerfile

  fetch-ledger:
    container_name: fetch-ledger
    build:
      context: ./prediction-market-ledger
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    logging:
      driver: none

  fetch-oracle:
    container_name: fetch-oracle
    build:
      context: ./prediction-market-oracle
      dockerfile: ./Dockerfile
